export const inventarioCilindros = [
  { cilindro: 65, cantidad: 7, repeat_in: 8.125, maquina: 'MARK ANDY' },
  { cilindro: 66, cantidad: 5, repeat_in: 8.25, maquina: 'MARK ANDY' },
  { cilindro: 68, cantidad: 1, repeat_in: 8.5, maquina: 'MARK ANDY' },
  { cilindro: 69, cantidad: 5, repeat_in: 8.625, maquina: 'MARK ANDY' },
  { cilindro: 72, cantidad: 6, repeat_in: 9, maquina: 'MARK ANDY' },
  { cilindro: 74, cantidad: 9, repeat_in: 9.25, maquina: 'MARK ANDY' },
  { cilindro: 75, cantidad: 6, repeat_in: 9.375, maquina: 'MARK ANDY' },
  { cilindro: 76, cantidad: 18, repeat_in: 9.5, maquina: 'MARK ANDY' },
  { cilindro: 78, cantidad: 17, repeat_in: 9.75, maquina: 'MARK ANDY' },
  { cilindro: 79, cantidad: 6, repeat_in: 9.875, maquina: 'MARK ANDY' },
  { cilindro: 80, cantidad: 2, repeat_in: 10, maquina: 'MARK ANDY' },
  { cilindro: 81, cantidad: 4, repeat_in: 10.125, maquina: 'MARK ANDY' },
  { cilindro: 82, cantidad: 25, repeat_in: 10.25, maquina: 'MARK ANDY' },
  { cilindro: 84, cantidad: 9, repeat_in: 10.5, maquina: 'MARK ANDY' },
  { cilindro: 85, cantidad: 5, repeat_in: 10.625, maquina: 'MARK ANDY' },
  { cilindro: 87, cantidad: 2, repeat_in: 10.875, maquina: 'MARK ANDY' },
  { cilindro: 88, cantidad: 7, repeat_in: 11, maquina: 'MARK ANDY' },
  { cilindro: 90, cantidad: 11, repeat_in: 11.25, maquina: 'MARK ANDY' },
  { cilindro: 91, cantidad: 3, repeat_in: 11.375, maquina: 'MARK ANDY' },
  { cilindro: 92, cantidad: 1, repeat_in: 11.5, maquina: 'MARK ANDY' },
  { cilindro: 93, cantidad: 3, repeat_in: 11.625, maquina: 'MARK ANDY' },
  { cilindro: 95, cantidad: 6, repeat_in: 11.875, maquina: 'MARK ANDY' },
  { cilindro: 96, cantidad: 6, repeat_in: 12, maquina: 'MARK ANDY' },
  { cilindro: 97, cantidad: 6, repeat_in: 12.125, maquina: 'MARK ANDY' },
  { cilindro: 98, cantidad: 15, repeat_in: 12.25, maquina: 'MARK ANDY' },
  { cilindro: 99, cantidad: 9, repeat_in: 12.375, maquina: 'MARK ANDY' },
  { cilindro: 102, cantidad: 2, repeat_in: 12.75, maquina: 'MARK ANDY' },
  { cilindro: 104, cantidad: 11, repeat_in: 13, maquina: 'MARK ANDY' },
  { cilindro: 105, cantidad: 3, repeat_in: 13.125, maquina: 'MARK ANDY' },
  { cilindro: 106, cantidad: 2, repeat_in: 13.25, maquina: 'MARK ANDY' },
  { cilindro: 107, cantidad: 1, repeat_in: 13.375, maquina: 'MARK ANDY' },
  { cilindro: 108, cantidad: 6, repeat_in: 13.5, maquina: 'MARK ANDY' },
  { cilindro: 110, cantidad: 6, repeat_in: 13.75, maquina: 'MARK ANDY' },
  { cilindro: 111, cantidad: 3, repeat_in: 13.875, maquina: 'MARK ANDY' },
  { cilindro: 114, cantidad: 8, repeat_in: 14.25, maquina: 'MARK ANDY' },
  { cilindro: 116, cantidad: 2, repeat_in: 14.5, maquina: 'MARK ANDY' },
  { cilindro: 117, cantidad: 5, repeat_in: 14.625, maquina: 'MARK ANDY' },
  { cilindro: 120, cantidad: 2, repeat_in: 15, maquina: 'MARK ANDY' },
  { cilindro: 122, cantidad: 6, repeat_in: 15.25, maquina: 'MARK ANDY' },
  { cilindro: 123, cantidad: 4, repeat_in: 15.375, maquina: 'MARK ANDY' },
  { cilindro: 130, cantidad: 4, repeat_in: 16.25, maquina: 'MARK ANDY' },
  { cilindro: 132, cantidad: 3, repeat_in: 16.5, maquina: 'MARK ANDY' },
  { cilindro: 141, cantidad: 2, repeat_in: 17.625, maquina: 'MARK ANDY' },
  { cilindro: 60, cantidad: 5, repeat_in: 7.5, maquina: 'STACK' },
  { cilindro: 65, cantidad: 7, repeat_in: 8.125, maquina: 'STACK' },
  { cilindro: 70, cantidad: 5, repeat_in: 8.75, maquina: 'STACK' },
  { cilindro: 82, cantidad: 6, repeat_in: 10.25, maquina: 'STACK' },
  { cilindro: 96, cantidad: 5, repeat_in: 12, maquina: 'STACK' },
  { cilindro: 110, cantidad: 5, repeat_in: 13.75, maquina: 'STACK' }
];
